lang: en-US
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
remote_theme: mmistakes/minimal-mistakes
title: Master Notions
description: Behind The Mythology of Glenn Greenwald
header:
  image: assets/images/twitter-cardbr.jpg
  og_image: assets/images/twitter-card2.jpg
twitter:  
  image: https://masternotions.com/assets/images/twitter-card2.jpg
  username: "ggreenwald"
  title: Master Notions
  description: Mythology of GG
google_analytics: G-J73QXGV4YW
minimal_mistakes_skin: "mint"
sidebar:
 - image: /assets/images/EshEH_WU4AE7WXV.jpg
repository: alansfr/alansfr.github.io
url: "https://masternotions.com"
baseurl: "/"
logo: assets/images/hippopotamus-head.svg
atom_feed:
  hide: true
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-J73QXGV4YW"
    anonymize_ip: false # default

